# Site settings

author: Cristian Perez Brokate
title: Cristian Perez Brokate
email: cperez at kernix.com
description: > # this means to ignore newlines until "baseurl:"
        Data scientist, programming, technology, linux, vim, mutt, git, python, nodejs, R, modelling studies, visualization.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cristianpb.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: https://twitter.com/cris_perez_b
# Needed by jekyll-seo-tag
twitter: 
  username: cris_perez_b
logo: '/assets/favicons/android-icon-192x192.png' 
linkedin_username: cristianperezbrokate
github_username:  cristianpb
researchgate_username:  Cristian_Perez_Brokate
disqus:
  shortname: cristianpb-github-io
google_analytics: UA-68913933-2
paginate: 6
paginate_path: '/blog/:num'
google-site-verification: 'dadHYln91lNA-p2JDYCrivQ6etkGJeqk1Dz1GpshKk0'
social:
  name: Cristian Perez Brokate
  links:
    - https://twitter.com/cris_perez_b
    - https://www.linkedin.com/in/cristianperezbrokate
    - https://github.com/cristianpb
    - https://scholar.google.com/citations?hl=en&user=rIdjCp0AAAAJ
    - https://www.researchgate.net/profile/Cristian_Perez_Brokate
    - https://www.kaggle.com/cristianpb
author:
  name: Cristian Perez Brokate
  linkedin: https://www.linkedin.com/in/cristianperezbrokate
  github: https://github.com/cristianpb
  twitter: https://twitter.com/cris_perez_b
  google: https://scholar.google.com/citations?hl=en&user=rIdjCp0AAAAJ
  researchgate: https://www.researchgate.net/profile/Cristian_Perez_Brokate
  kaggle: https://www.kaggle.com/cristianpb
  medium: https://medium.com/@cristianpb
 
# Build settings
sass:
    style: compressed
markdown: kramdown
kramdown:
  parse_block_html: true
plugins:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji
exclude:
  - drafts
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - gulpfile.js
 
defaults:
    - {scope: {type: posts}, values: {layout: post, permalink: '/blog/:title'}}

include:
  - _pages

