# Site settings

title: Cristian Perez Brokate
email: cperez at kernix.com
description: > # this means to ignore newlines until "baseurl:"
        Data scientist in Paris area. I use machine learning, data science and deep learning for data projects using python, javascript & R. I build interactive dashboards and web applications using nodejs, flask, python, Angular, docker.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cristianpb.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: https://twitter.com/cris_perez_b
# Needed by jekyll-seo-tag
twitter: 
  username: cris_perez_b
logo: '/assets/img/avatar.png' 
linkedin_username: cristianperezbrokate
github_username:  cristianpb
researchgate_username:  Cristian_Perez_Brokate
disqus:
  shortname: cristianpb-github-io
social:
  name: Cristian Perez Brokate
  links:
    - https://twitter.com/cris_perez_b
    - https://www.linkedin.com/in/cristianperezbrokate
    - https://github.com/cristianpb
    - https://scholar.google.com/citations?hl=en&user=rIdjCp0AAAAJ
    - https://www.researchgate.net/profile/Cristian_Perez_Brokate
    - https://www.kaggle.com/cristianpb
author:
  name: Cristian Perez Brokate
  github: cristianpb
  medium: "@cristianpb"
  twitter: cris_perez_b
  linkedin: cristianperezbrokate
  kaggle: cristianpb

socialnetworks:
  github: https://github.com/cristianpb
  medium: https://medium.com/@cristianpb
  twitter: https://twitter.com/cris_perez_b
  linkedin: https://www.linkedin.com/in/cristianperezbrokate
  kaggle: https://www.kaggle.com/cristianpb
  google: https://scholar.google.com/citations?hl=en&user=rIdjCp0AAAAJ
  researchgate: https://www.researchgate.net/profile/Cristian_Perez_Brokate

google_analytics: UA-68913933-2
google_site_verification: dadHYln91lNA-p2JDYCrivQ6etkGJeqk1Dz1GpshKk0

# algolia search
algolia:
  application_id: 'Z1GMX6PWB9'
  index_name: cristianpb
  files_to_exclude:
    - _pages/*.html
    - _iframes/*.html
    - blog/*.html

# Color the browser elements #
color-browser: "#03abea"
apple-status-bar-style: "black-translucent"
 
# Build settings
sass:
    style: compressed
markdown: kramdown
kramdown:
  parse_block_html: true
plugins:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

collections:
  iframes:
    output: true
    permalink: /:collection/:name
  external:
    output: true
    permalink: /:collection/:name

exclude:
  - drafts
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - gulpfile.js
  - package.json
  - package-lock.json
 
defaults:
    - {scope: {type: posts}, values: {layout: post, permalink: '/blog/:title'}}
    - {scope: {path: "", layout: default, type: "pages"}, values: {image: {
      path: '/assets/img/avatar.png', width: 200, height: 200}}}
    - {scope: {path: "blog/"}, values: {permalink: '/blog/:title'}}

include:
  - _pages

