# Site settings

author: Cristian Perez
title: Cristian Perez
email: cperez at kernix.com
description: > # this means to ignore newlines until "baseurl:"
        Data science, programming, technology, vim, mutt, git, node, python, nodejs, R, physics, corrosion, modelling studies, visualization.
baseurl: "" # the subpath of your site, e.g. /blog
url: http://cristianpb.github.io/ "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: https://twitter.com/cris_perez_b
twitter:
  username: cris_perez_b
linkedin_username: cristianperezbrokate
github_username:  cristianpb
researchgate_username:  Cristian_Perez_Brokate
disqus:
  shortname: cristianpb-github-io
google_analytics: UA-68913933-2
paginate: 12
paginate_path: '/blog/:num'


# Build settings
sass:
    style: compressed
markdown: kramdown
#kramdown:
#  parse_block_html: true
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-time-to-read
  - jemoji
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - reveal.js/index.html
  - reveal.js/plugin/markdown/example.html
  - reveal.js/plugin/notes/notes.html
  - reveal.js/plugin/notes-server/notes.html
  - reveal.js/test/
  - reveal.js/*.md
  - reveal.js/Gruntfile.js
  - reveal.js/package.json
 
defaults:
    - {scope: {type: posts}, values: {layout: post, permalink: '/blog/:title'}}

include:
  - _pages

