---
name: Tests html

on: [push]

jobs:
  test:
    name: Test html consistency

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Install dependencies and build
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec jekyll build
      - name: Test html
        run: |
          gem install html-proofer
          htmlproofer --url-ignore "/www.linkedin.com/"  --http-status-ignore "0"  --check_opengraph --assume-extension  ./_site
